### ISSUE TITLE
Deploy to Maven Central Repository

### ISSUE THREAD

**Issue by ralphcollett** [simple-http/simple-http#12]
https://central.sonatype.org/pages/ossrh-guide.html

Awaiting this Jira - https://issues.sonatype.org/browse/OSSRH-40600

**Comment by tobyweston** [comment]
Good summary but I’m not interested in Rultor

**Comment by ralphcollett** [comment]
Thanks, I just commented here to get the link between my 2 laptops. Haven’t read it yet.
