### ISSUE TITLE
Repackage as simple-http.com

### ISSUE THREAD

**Issue by ralphcollett** [simple-http/simple-http#13]
Need to be done as a precursor to #12 [https://issues.sonatype.org/browse/OSSRH-40600](https://issues.sonatype.org/browse/OSSRH-40600)

**Comment by ralphcollett** [comment]
[Java recommends](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) "simple_http". I think I prefer "simplehttp" or just "http" what do you think @tobyweston?

**Comment by tobyweston** [comment]
I vote for...
 - [ ] com.simple.http
 - [ ] simple.http
 - [ ] http
 - [ ] simplehttp
 - [ ] simple_http

**Comment by ralphcollett** [comment]
I choose to keep my vote anonymous.

**Comment by ralphcollett** [comment]
The votes have been counted and it is a landslide victory for simplehttp.
