### ISSUE TITLE
Make TravisCI work with simple-http/simple-http

### ISSUE THREAD

**Issue by tobyweston** [simple-http/simple-http#14]
We moved from https://github.com/tobyweston/simple-http to https://github.com/simple-http/simple-http and I'm not sure if Travis will pick this up.

Make sure it builds on the next commit.

**Comment by ralphcollett** [comment]
@tobyweston if you give me admin access to the repo I'll take care of this. Just need to follow [these instructions](https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo) and update the README.md link.
